--- #YAML:1.0
name:                Gtk2-Ex-TiedListColumn
version:             1
abstract:            Tie an array to a Gtk2-Perl TreeModel.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Gtk2:                          0
    List::Util:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/gtk2-ex-tiedlistcolumn/index.html
